package com.highserpot.tf.store

enum class ScreenStatus {
    MODE_BASIC, MODE_BASIC_SMARTKEY_OFF, MODE_BASIC_SMARTKEY_ON, SKIP, SKIP_POPUP, MODE_POWER_SAVE, BAG_BASIC, BAG_DISSASSEMBLE_ACTIVE, BAG_DISSASSEMBLE_ACTIVE_GENERAL, BAG_DISSASSEMBLE_ACTIVE_ADVANCED, BAG_DISSASSEMBLE_SELECT, BAG_DISSASSEMBLE_POPUP, BAG_DISSASSEMBLE_RESULT,UPDATE_TEAM,MINI_POPUP
}